channels:
- conda-forge
dependencies:
- python=3.7
- cython
- dill
- future
- ipywidgets
- jupyterlab
- h5py
- matplotlib
- nodejs
- numba
- numpy
- numpydoc
- pandas
- pip
- scikit-image
- scikit-learn
- scipy
- tifffile
- tqdm
- widgetsnbextension
